#ifndef AXIS_SNIFFER0_REGISTERS_H
#define AXIS_SNIFFER0_REGISTERS_H

#define CONTROL 0x0
#define TRANSACTION_COUNT 0x4
#define TRANSACTION_VALUE 0x8
#define GLOBAL_STATUS 0xC
#define FIFO_STATUS 0x10
#define SCRATCHPAD 0x14
#define CTRL_STATUS 0x18

#define CONTROL_SW_RESETN_MASK 0x1
#define CONTROL_SW_RESETN_SHIFT 0
#define CONTROL_SW_RESETN (0x1)

#define TRANSACTION_COUNT_COUNT_MASK 0xFFFFFFFF
#define TRANSACTION_COUNT_COUNT_SHIFT 0

#define TRANSACTION_VALUE_DATA_MASK 0xFFFFFFFF
#define TRANSACTION_VALUE_DATA_SHIFT 0

#define GLOBAL_STATUS_FIFO_DOUT_VALID_MASK 0x1
#define GLOBAL_STATUS_FIFO_DOUT_VALID_SHIFT 1
#define GLOBAL_STATUS_FIFO_DOUT_VALID (0x2)
#define GLOBAL_STATUS_TRANSACTION_OVERFLOW_MASK 0x1
#define GLOBAL_STATUS_TRANSACTION_OVERFLOW_SHIFT 0
#define GLOBAL_STATUS_TRANSACTION_OVERFLOW (0x1)

#define FIFO_STATUS_FIFO_USED_MASK 0xFFFFFFFF
#define FIFO_STATUS_FIFO_USED_SHIFT 0

#define SCRATCHPAD_SCRATCH_MASK 0xFFFFFFFF
#define SCRATCHPAD_SCRATCH_SHIFT 0

#define CTRL_STATUS_S_AXIS_TVALID_MASK 0x1
#define CTRL_STATUS_S_AXIS_TVALID_SHIFT 0
#define CTRL_STATUS_S_AXIS_TVALID (0x1)
#define CTRL_STATUS_M_AXIS_TREADY_MASK 0x1
#define CTRL_STATUS_M_AXIS_TREADY_SHIFT 1
#define CTRL_STATUS_M_AXIS_TREADY (0x2)

#endif
