#ifndef SW_DSP_REGISTERS_H
#define SW_DSP_REGISTERS_H

#define CONTROL 0x0
#define STATUS_RESET 0x4
#define STATUS 0x8
#define DIN_FIFO_USED 0xC
#define DOUT_FIFO_USED 0x10

#define CONTROL_ENGAUGE_LOOPBACK_MASK 0x1
#define CONTROL_ENGAUGE_LOOPBACK_SHIFT 0
#define CONTROL_ENGAUGE_LOOPBACK (0x1)

#define STATUS_RESET_M_AXIS_OVERFLOW_MASK 0x1
#define STATUS_RESET_M_AXIS_OVERFLOW_SHIFT 1
#define STATUS_RESET_M_AXIS_OVERFLOW (0x2)
#define STATUS_RESET_S_AXIS_UNDERFLOW_MASK 0x1
#define STATUS_RESET_S_AXIS_UNDERFLOW_SHIFT 0
#define STATUS_RESET_S_AXIS_UNDERFLOW (0x1)

#define STATUS_M_AXIS_OVERFLOW_MASK 0x1
#define STATUS_M_AXIS_OVERFLOW_SHIFT 1
#define STATUS_M_AXIS_OVERFLOW (0x2)
#define STATUS_S_AXIS_UNDERFLOW_MASK 0x1
#define STATUS_S_AXIS_UNDERFLOW_SHIFT 0
#define STATUS_S_AXIS_UNDERFLOW (0x1)

#define DIN_FIFO_USED_FIFO_USED_MASK 0xFFFFFFFF
#define DIN_FIFO_USED_FIFO_USED_SHIFT 0

#define DOUT_FIFO_USED_FIFO_USED_MASK 0xFFFFFFFF
#define DOUT_FIFO_USED_FIFO_USED_SHIFT 0

#endif
