#ifndef MCP3221_REGISTERS_H
#define MCP3221_REGISTERS_H

#define CONTROL 0x0
#define SAMPLE_RATE_DIVIDER 0x4
#define DATA 0x8
#define STATUS 0xC

#define CONTROL_DEVICE_ADDRESS_MASK 0x7F
#define CONTROL_DEVICE_ADDRESS_SHIFT 1
#define CONTROL_SW_RESETN_MASK 0x1
#define CONTROL_SW_RESETN_SHIFT 0
#define CONTROL_SW_RESETN (0x1)

#define SAMPLE_RATE_DIVIDER_SAMPLE_RATE_DIVIDER_MASK 0xFFFFFFFF
#define SAMPLE_RATE_DIVIDER_SAMPLE_RATE_DIVIDER_SHIFT 0

#define DATA_DATA_MASK 0xFFFF
#define DATA_DATA_SHIFT 0

#define STATUS_DOUT_VALID_MASK 0x1
#define STATUS_DOUT_VALID_SHIFT 1
#define STATUS_DOUT_VALID (0x2)
#define STATUS_DIN_READY_MASK 0x1
#define STATUS_DIN_READY_SHIFT 0
#define STATUS_DIN_READY (0x1)

#endif
